---
- name: Kubernetes Master

  hosts: master
  remote_user: root
  become: false

  roles:
  - etcd
  - role: flannel
    mode: master
  - docker
  - role: kubernetes
    mode: master

- name: Kubernetes Nodes

  hosts: nodes
  remote_user: root
  become: false

  roles:
  - role: flannel
    mode: node
  - docker
  - role: kubernetes
    mode: node
