---
- name: Kubernetes Master

  hosts: master
  remote_user: root
  become: false
  vars_files:
    - internal_ips.yml

  roles:
  - scw-base
  - etcd
  - role: flannel
    mode: master
  - docker
  - role: kubernetes
    mode: master
  - skydns

- name: Kubernetes Nodes

  hosts: nodes
  remote_user: root
  become: false
  vars_files:
    - internal_ips.yml

  roles:
  - role: flannel
    mode: node
  - docker
  - role: kubernetes
    mode: node
