- name: Install flanneld
  include: ../../includes/install_binaries.yml
  vars:
    binaries:
      name: flannel
      version: "{{ version.flannel }}"
      commands:
        - flanneld

- name: Create flannel env directory
  file: path=/var/lib/flannel state=directory recurse=false

- name: Ensure that target directory /etc/kubernetes exists
  file: path=/etc/kubernetes state=directory recurse=false

- name: Add flannel_init.sh for setting flannel network
  template: src={{ mode }}/flannel_init.sh dest=/etc/kubernetes/flannel_init.sh mode=0755

- name: Install flannel service definition
  template: src={{ mode }}/flannel.service dest=/lib/systemd/system/flannel.service owner=root group=root mode=0644
  register: result

- name: Reload systemd when service definition changed
  command: systemctl daemon-reload
  when: result|changed

- name: Restart flannel
  service: name=flannel enabled=yes state=restarted
